//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMR_Dispatches
    {
        public int Id { get; set; }
        public int Dispatch_Id { get; set; }
        public string Commodity_Type { get; set; }
        public string Destination { get; set; }
        public string Sender_Name { get; set; }
        public string Sender_Address { get; set; }
        public string Sender_PrefixVat_Id { get; set; }
        public string Sender_VAT_Id { get; set; }
        public string Sender_Email { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public Nullable<System.DateTime> Edited_At { get; set; }
        public Nullable<System.DateTime> Deleted_At { get; set; }
    }
}
