//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch
    {
        public int Id { get; set; }
        public string Dispatch_Number { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Car_Id { get; set; }
        public string Carrier_Name { get; set; }
        public string Carrier_Address { get; set; }
        public string Carrier_VAT_Id { get; set; }
        public string Carrier_Email { get; set; }
        public string Receiver_Name { get; set; }
        public string Receiver_Address { get; set; }
        public string Receiver_VAT_Id { get; set; }
        public string Receiver_Email { get; set; }
        public string Duty_Doc_Id { get; set; }
        public Nullable<int> Number_Of_Positions { get; set; }
        public string CMR_Id { get; set; }
        public Nullable<bool> If_PDF_And_Sent { get; set; }
        public Nullable<bool> If_CMR_And_Sent { get; set; }
        public Nullable<bool> If_CMR { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public Nullable<System.DateTime> Edited_At { get; set; }
        public Nullable<System.DateTime> Deleted_At { get; set; }
    }
}
