//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Container_Id { get; set; }
        public string ATB { get; set; }
        public string Pickup_PIN { get; set; }
        public Nullable<System.DateTime> Date_Of_Arrival { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public int Creator_Id { get; set; }
        public string Order_Number { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string VAT_Id { get; set; }
        public string Email { get; set; }
        public int Num_of_Positions { get; set; }
        public Nullable<bool> If_PDF_And_Sent { get; set; }
        public Nullable<bool> If_Delivery_Generated { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public string Terminal { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public Nullable<System.DateTime> Edited_At { get; set; }
        public Nullable<System.DateTime> Deleted_At { get; set; }
    }
}
