//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_Positions
    {
        public int Id { get; set; }
        public int Order_id { get; set; }
        public int Amount { get; set; }
        public decimal Weight_Gross { get; set; }
        public Nullable<int> Amount_Received { get; set; }
        public Nullable<decimal> Weight_Gross_Received { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public Nullable<System.DateTime> Edited_At { get; set; }
        public Nullable<System.DateTime> Deleted_At { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Unit_Weight { get; set; }
    }
}
